/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.gpaproject;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

import javax.swing.JOptionPane;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author maa
 */
public class Gpacalc extends javax.swing.JFrame {

    /**
     * Creates new form Gpacalc
     */
	
    public Gpacalc() {
    	setTitle("Recording The Student's GPA Into The Database");
        initComponents();
        this.setLocationRelativeTo(null);
    }
    public double ret(String m,int n) {
            double l=0;
            if(m=="A") {
		            l = 4*n;
            }
       	    else if(m=="A-") {
		           l = 3.7*n;
            }
            else if(m == "B+") {
		             l = 3.3*n;
            }
            else if(m=="B") {
		             l=3*n;
            }
            else if(m=="B-") {
		            l=2.7*n;
            }
            else if(m=="C+") {
	                l=2.3*n;
            }
            else if(m=="C") {
		              l=2*n;
            }
            else if(m=="C-") {
	            	l=1.7*n;
            }
            else if(m=="D+") {
		           l=1.3*n;
            }
            else if(m=="D") {
		           l=1*n;
            }
            else if(m=="F") {
	            	l=0*n;
            }
            
           return l;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        vp0 = new javax.swing.JTextField();
        vp1 = new javax.swing.JTextField();
        vp2 = new javax.swing.JTextField();
        vp3 = new javax.swing.JTextField();
        vp4 = new javax.swing.JTextField();
        vp5 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtbox0 = new javax.swing.JComboBox<>();
        txtbox1 = new javax.swing.JComboBox<>();
        txtbox2 = new javax.swing.JComboBox<>();
        txtbox3 = new javax.swing.JComboBox<>();
        txtbox4 = new javax.swing.JComboBox<>();
        txtbox5 = new javax.swing.JComboBox<>();
        calc = new javax.swing.JButton();
        txtid = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("DBMS");

        jTextField2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setText("Math-3");

        jTextField3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.setText("Visual Programming");

        jTextField4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField4.setText("Computer Architecture");
        
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jTextField5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField5.setText("Security");

        jTextField6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField6.setText("Creative");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("GPA Calculator");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Courses");

        vp0.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        vp0.setText("0");

        vp1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        vp1.setText("0");

        vp2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        vp2.setText("0");

        vp3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        vp3.setText("0");

        vp4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        vp4.setText("0");

        vp5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        vp5.setText("0");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Credits");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Grade");

        txtbox0.setEditable(true);
        txtbox0.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D+", "D", "F" }));

        txtbox1.setEditable(true);
        txtbox1.setModel(new DefaultComboBoxModel(new String[] {"A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D+", "D", "F"}));

        txtbox2.setEditable(true);
        txtbox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D+", "D", "F" }));

        txtbox3.setEditable(true);
        txtbox3.setModel(new DefaultComboBoxModel(new String[] {"A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D+", "D", "F"}));

        txtbox4.setEditable(true);
        txtbox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D+", "D", "F" }));

        txtbox5.setEditable(true);
        txtbox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D+", "D", "F" }));

        calc.setBackground(new java.awt.Color(81, 142, 40));
        calc.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        calc.setText("Calculate");
        
        calc.addActionListener(new java.awt.event.ActionListener() {
        	
            public void actionPerformed(java.awt.event.ActionEvent evt) {              
                
                    // TODO add your handling code here:
                 int []arr= {Integer.parseInt(vp0.getText()),Integer.parseInt(vp1.getText()),Integer.parseInt(vp2.getText()),
                 Integer.parseInt(vp3.getText()),Integer.parseInt(vp4.getText()),Integer.parseInt(vp4.getText())};
            		 
            	double []arr1= {ret((String)txtbox0.getSelectedItem(), arr[0]),ret((String)txtbox1.getSelectedItem(), arr[1]),
            	ret((String)txtbox2.getSelectedItem(), arr[2]),ret((String)txtbox3.getSelectedItem(), arr[3]),
            	ret((String)txtbox4.getSelectedItem(), arr[4]),ret((String)txtbox5.getSelectedItem(), arr[5])};
            	
            	int allcredit = 0;
            	double allpoints = 0;
            	for(int i = 0;i < 6;i++) {
                  allcredit += arr[i];
               }
            	for(int i = 0; i < 6 ;i++) {
            	    allpoints += arr1[i];
            	}
                if("0".equals(txtid.getText())){
                        JOptionPane.showMessageDialog(null, "Please enter the id");
                       return ;
                }
                
                double gpA = 0;
            	if(allcredit != 0) {
            	    gpA = allpoints / allcredit;
                        JOptionPane.showMessageDialog(null,"Your GPA is : " + String.format("%.2f", gpA) , "GPA" , JOptionPane.INFORMATION_MESSAGE);
            	}
            	else {
            	    JOptionPane.showMessageDialog(null, "Please add The Credit Hours" ,"ERROR" ,JOptionPane.ERROR_MESSAGE);
            	}
          
            	Student.setGpa(gpA);
            	
                Student.setid( Long.parseLong(txtid.getText()));   
                
            	Student st = new Student();
                insert(st);
                
            }
        });
        

        txtid.setText("0");
        txtid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidActionPerformed(evt); 
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("id");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1Layout.setHorizontalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        						.addGroup(jPanel1Layout.createSequentialGroup()
        							.addContainerGap()
        							.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        								.addComponent(jTextField1, 150, 150, 150)
        								.addComponent(jTextField5, 150, 150, 150)
        								.addComponent(jTextField2, 150, 150, 150)
        								.addComponent(jTextField3, 150, 150, 150)
        								.addComponent(jTextField6, 150, 150, 150)))
        						.addGroup(jPanel1Layout.createSequentialGroup()
        							.addGap(19)
        							.addComponent(jLabel2, GroupLayout.PREFERRED_SIZE, 82, GroupLayout.PREFERRED_SIZE))
        						.addGroup(jPanel1Layout.createSequentialGroup()
        							.addContainerGap()
        							.addComponent(jTextField4, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
        					.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        						.addGroup(jPanel1Layout.createSequentialGroup()
        							.addGap(46)
        							.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING)
        								.addComponent(vp1, GroupLayout.PREFERRED_SIZE, 45, GroupLayout.PREFERRED_SIZE)
        								.addComponent(vp0, GroupLayout.PREFERRED_SIZE, 45, GroupLayout.PREFERRED_SIZE)
        								.addComponent(vp2, GroupLayout.PREFERRED_SIZE, 45, GroupLayout.PREFERRED_SIZE)
        								.addComponent(vp3, GroupLayout.PREFERRED_SIZE, 45, GroupLayout.PREFERRED_SIZE)
        								.addComponent(vp4, GroupLayout.PREFERRED_SIZE, 45, GroupLayout.PREFERRED_SIZE)
        								.addComponent(vp5, GroupLayout.PREFERRED_SIZE, 45, GroupLayout.PREFERRED_SIZE)))
        						.addGroup(jPanel1Layout.createSequentialGroup()
        							.addGap(27)
        							.addComponent(jLabel3, GroupLayout.PREFERRED_SIZE, 82, GroupLayout.PREFERRED_SIZE)))
        					.addGap(24)
        					.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING)
        						.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        							.addComponent(txtbox0, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        							.addComponent(txtbox2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        							.addComponent(txtbox3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        							.addComponent(txtbox1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        							.addComponent(txtbox4, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        							.addComponent(txtbox5, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        						.addComponent(jLabel4, GroupLayout.PREFERRED_SIZE, 82, GroupLayout.PREFERRED_SIZE)))
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addGap(66)
        					.addComponent(jLabel5, GroupLayout.PREFERRED_SIZE, 55, GroupLayout.PREFERRED_SIZE)
        					.addGap(18)
        					.addComponent(txtid, GroupLayout.PREFERRED_SIZE, 172, GroupLayout.PREFERRED_SIZE))
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addGap(180)
        					.addComponent(calc))
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addGap(159)
        					.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 129, GroupLayout.PREFERRED_SIZE)))
        			.addContainerGap(59, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addGap(16)
        			.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 42, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel2)
        				.addComponent(jLabel3)
        				.addComponent(jLabel4))
        			.addGap(18)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING, false)
        				.addComponent(jTextField1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        					.addComponent(vp0, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        					.addComponent(txtbox0, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addGap(8)
        					.addComponent(txtbox1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        					.addGap(18)
        					.addComponent(txtbox2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        						.addGroup(jPanel1Layout.createSequentialGroup()
        							.addGap(12)
        							.addComponent(jTextField2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        						.addGroup(jPanel1Layout.createSequentialGroup()
        							.addGap(14)
        							.addComponent(vp1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
        					.addPreferredGap(ComponentPlacement.UNRELATED)
        					.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(jTextField3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        						.addComponent(vp2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        					.addGap(12)
        					.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(jTextField4, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        						.addComponent(vp3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        						.addComponent(txtbox3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        					.addGap(18)
        					.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(jTextField5, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        						.addComponent(vp4, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        						.addComponent(txtbox4, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        					.addGap(18)
        					.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(jTextField6, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        						.addComponent(vp5, GroupLayout.PREFERRED_SIZE, 26, GroupLayout.PREFERRED_SIZE)
        						.addComponent(txtbox5, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))))
        			.addGap(44)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(txtid, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jLabel5))
        			.addGap(27)
        			.addComponent(calc)
        			.addGap(39))
        );
        jPanel1.setLayout(jPanel1Layout);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    

  
    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed
    
   
  
    public static Connection getConnection() {
      	
       	try{  
			   Class.forName("com.mysql.cj.jdbc.Driver");
			   Connection con = DriverManager.getConnection("jdbc:mysql://197.161.61.184:3306/University","root","");  
			   Statement stmt = con.createStatement();
			   ResultSet rs = stmt.executeQuery("select * from Students"); 	
			   
			  //while(rs.next())     // to retrieve data from database
			  //  System.out.println(rs.getInt(1)+"  "+rs.getString(2)); 
			   
			   return con; 	
       	}catch(Exception e){ 
			    e.printStackTrace();
	   }
       	return null;
    }
       
    public static void insert(Student S) {
  
        Connection conn = getConnection();
        
        try {        
        	
       	String sql = "INSERT INTO `students` (`Student_ID`, `GPA`) VALUES (?, ?)";
    	PreparedStatement stm = conn.prepareStatement(sql);
    	stm.setLong(1, Student.getid());
    	stm.setDouble(2, Student.getGpa());
    	stm.execute();	
     
        JOptionPane.showMessageDialog(null," The Student's GPA has been added to the database Successfully !" , "GPA" , JOptionPane.INFORMATION_MESSAGE);
    	conn.close();
        }
        
        catch(SQLException ex) {
            JOptionPane.showMessageDialog(null," The Student's GPA could not added !" , " Welcome !" , JOptionPane.ERROR_MESSAGE);
        	ex.printStackTrace();
        }
       
    }
    
    private void txtidActionPerformed(java.awt.event.ActionEvent evt) {    //GEN-FIRST:event_txtidActionPerformed   
        // TODO add your handling code here: 
    }//GEN-LAST:event_txtidActionPerformed
    
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
    	
    	//getConnection();
    	
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gpacalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gpacalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gpacalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gpacalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gpacalc().setVisible(true);
            }
        });
        
   

    	
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JComboBox<String> txtbox0;
    private javax.swing.JComboBox<String> txtbox1;
    private javax.swing.JComboBox<String> txtbox2;
    private javax.swing.JComboBox<String> txtbox3;
    private javax.swing.JComboBox<String> txtbox4;
    private javax.swing.JComboBox<String> txtbox5;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField vp0;
    private javax.swing.JTextField vp1;
    private javax.swing.JTextField vp2;
    private javax.swing.JTextField vp3;
    private javax.swing.JTextField vp4;
    private javax.swing.JTextField vp5;
    // End of variables declaration//GEN-END:variables
}
